config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users, 
    controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
      invitations: "users/invitations"
    },
    path: '', 
    path_names: { sign_in: 'sign_in'}

  namespace :admin do 
    get 'dashboard', to: 'dashboard#index' # Ruta para el dashboard
    resources :users
    resources :joboffers
    resources :applications, only: %i[index show destroy] do
      member do
        patch :update_status
      end
    end
  end

  resources :joboffers, only: [:index, :show] do
    resources :applications, only: [:create]
  end
  
  resources :users, only: [:show, :edit, :update] do
    resources :applications, only: [:index] 
  end
  
  resources :applications, only: [:index, :create]
  # Defines the root path route ("/")
  
  root "joboffers#index"
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController

  def index
    total_applications = Application.count
    total_job_offers = Joboffer.count
    @new_applications_count = Application.where(:status_new => true).count
    @average_applications =  total_job_offers.zero? ? 0 : (total_applications.to_f / total_job_offers)
    

  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/views/admin/dashboard/index.html.erb
<%= content_for :title, "ADMIN"%>
<%= render 'shared/h1_title', title:"Dashboard" %>

<section class="container-fluid">
    <div class="d-md-flex flex-md-wrap justify-content-center gap-3 p-0">

        <div class="card col-10 col-md-3 border-0 shadow-lg mb-3 mx-auto">
            <div class="card-body text-center">
                <h5 class="card-title">Total User Registered</h5>    
                <p class="card-text">
                    <%= User.all.count%>
                </p>
                <div class="card-footer d-block justify-content-center">
                    <%= link_to "See all users", admin_users_path, class:"btn btn-outline-primary my-3"%>
                    <%= link_to "New invitation", new_user_invitation_path, class:"btn btn-outline-primary"%>
                </div>
            </div>
        </div>

        <div class="card col-10 col-md-3 border-0 shadow-lg mb-3 mx-auto">
            <div class="card-body text-center">
                <h5 class="card-title">Total Offers published</h5>    
                <p class="card-text">
                    <%= Joboffer.all.count%>
                </p>
                <div class="card-footer d-block justify-content-center gap-3">
                    <%= link_to "See all job offers", admin_joboffers_path, class:"btn btn-outline-primary my-3"%>
                    <%= link_to "New job offer", new_admin_joboffer_path, class:"btn btn-outline-primary"%>
                </div>
            </div>
        </div>
        
        <div class="card col-10 col-md-3 border-0 shadow-lg mb-3 mx-auto">
            <div class="card-body text-center">
                <h5 class="card-title">Average applies per job offer</h5>    
                <p class="card-text">
                    <%= @average_applications.round(2) %>
                </p>
                <h5 class="card-title">New Applications</h5>    
                <p class="card-text">
                    <%= @new_applications_count.round(2) %>
                </p>
                <div class="card-footer d-block justify-content-center gap-3">
                    <%= link_to "See all applications", admin_applications_path, class:"btn btn-outline-primary my-3"%>
                </div>
            </div>
        </div>
    </div>
    
</section>