config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users, 
    controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
      invitations: "users/invitations"
    },
    path: '', 
    path_names: { sign_in: 'sign_in'}

  namespace :admin do 
    get 'dashboard', to: 'dashboard#index' # Ruta para el dashboard
    resources :users
    resources :joboffers
    resources :applications, only: %i[index show destroy] do
      member do
        patch :update_status
      end
    end
  end

  resources :joboffers, only: [:index, :show] do
    resources :applications, only: [:create]
  end
  
  resources :users, only: [:show, :edit, :update] do
    resources :applications, only: [:index] 
  end
  
  resources :applications, only: [:index, :create]
  # Defines the root path route ("/")
  
  root "joboffers#index"
end

app/views/shared/_aside.html.erb
<%if user_signed_in? %>
<aside class="pt-3">
    <div class="container-fluid">
        <div class="card border-0 mx-auto my-2">
            <%= image_tag current_user&.profile_picture, class:"card-img-top img-thumbnail mx-auto",style:"width:100%;max-width:20vw;", alt:"No img available" if current_user.profile_picture.present? %>
            <div class="card-body">
                <span class="d-flex fs-6 text-center card-title"> <%=current_user&.email%></span>    
                <p class="card-text">
                    <%= link_to "My profile", current_user.admin == true ? admin_user_path(current_user) : user_path(current_user),class:"btn btn-outline-primary" %>
                <%unless current_user&.admin?%>
                <p class="card-text">
                    <% if current_user&.applications.present? %>
                        My applies:<%= current_user&.applications.count %>    
                        <ul class="list-group list-group-flush">
                            <%= link_to "My applies", user_applications_path(current_user), class:"btn btn-outline-primary"%>
                        </ul>    
                    <%else%>
                        No applies
                    <%end%>
                </p>
                <%end%>
            </div>
        </div>
    </div> 
    <!-- END PROFILE CONTAINER-->
    
    
</aside>
<%else%>
<aside class="d-none w-0">
</aside>
<%end%>

app/views/shared/_footer.html.erb
<footer class="container-fluid shadow"> 
    <div class="d-flex mb-0">
        <span class="w-100 text-center display-6 fs-6">&copy; Internal Platform, 2024</span>
    </div>
    <div class="d-flex justify-content-center gap-3 mb-0">
        <i class="bi bi-github fs-3"></i>
        <i class="bi bi-patch-question fs-3"></i>
    </div>
</footer>

app/views/shared/_h1_title.html.erb
<section class="d-inline-flex align-items-center m-0 p-0 mb-5">
    <%= link_to :back, class:"btn btn-outline-primary ms-2 border-0" do%><i class="bi bi-arrow-left"></i><%end%>
    <h1 class="display-3 ms-5 px-3"><%= title %></h1>
</section> 

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light px-2" data-turbo-permanent>
    <!-- Brand -->
            <%= link_to "Internal platform", root_path, class:"navbar-brand" %>
            <button class="navbar-toggler d-lg-none ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        <!---->
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav w-100">
            <!-- admin menu -->
                <% if current_user&.admin? %>
                <li class="nav-item">
                    <%= link_to "Dashboard",  admin_dashboard_path, class:"btn btn-success p-1"%>
                </li>
                <%end%>
            <!-- end admin menu -->
                <li class="nav-item">
                    <%= link_to "See the offers",  joboffers_path, class:"nav-link"%>
                </li>

                <li class="d-md-none nav-item dropdown mb-2">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-bs-toggle="dropdown" aria-haspopup="true"aria-expanded="false">
                        <strong>@<%= current_user&.name || current_user&.email %></strong>
                    </a>
                    <div class="dropdown-menu mx-0 p-0" aria-labelledby="dropdownId">
                        <%= link_to "My profile", current_user.admin == true ? admin_user_path(current_user) : user_path(current_user),class:"dropdown-item" %>
                        
                        <%= link_to "My applies", user_applications_path(current_user), class:"dropdown-item" unless current_user.admin == true %>

                    </div>
                </li>
                
                <div class="dropdown-divider"></div>
                
                <li class="nav-item me-auto">
                    <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class:"btn btn-primary" %>
                </li>

            </ul>
        
        </div>    

</nav>

app/views/shared/_notice_alert.html.erb
      <div class="d-flex p-0 m-1">
        <% if flash[:notice] %>
            <div class="alert alert-success" role="alert">
                <%= flash[:notice] %>
            </div>
        <% end %>

        <% if flash[:alert] %>
            <div class="alert alert-danger" role="alert">
                <%= flash[:alert] %>
            </div>
        <% end %>
      </div>