config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users, 
    controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
      invitations: "users/invitations"
    },
    path: '', 
    path_names: { sign_in: 'sign_in'}

  namespace :admin do 
    get 'dashboard', to: 'dashboard#index' # Ruta para el dashboard
    resources :users
    resources :joboffers
    resources :applications, only: %i[index show destroy] do
      member do
        patch :update_status
      end
    end
  end

  resources :joboffers, only: [:index, :show] do
    resources :applications, only: [:create]
  end
  
  resources :users, only: [:show, :edit, :update] do
    resources :applications, only: [:index] 
  end
  
  resources :applications, only: [:index, :create]
  # Defines the root path route ("/")
  
  root "joboffers#index"
end

app/models/joboffer.rb
class Joboffer < ApplicationRecord
    belongs_to :user
    
    has_many :applications, dependent: :destroy
    
    validates :title, presence: true
    validates :description, presence: true
    

end

app/controllers/admin/joboffers_controller.rb
class Admin::JoboffersController < ApplicationController
    before_action :authenticate_admin
    before_action :set_joboffer, only: %i[show edit update destroy]
    
    def index
        @joboffers = Joboffer.all
    end
    
    def new
        @joboffer = Joboffer.new
    end
    
    def show
        @applications = @joboffer.applications
    end
    
    def edit
    end

    def create
        @joboffer = Joboffer.new(joboffer_params)
        @joboffer.user_id = current_user.id
        @joboffer.salary = @joboffer.salary.to_s.gsub(/[^\d\.]/, '').to_f
    
        respond_to do |format|
            if @joboffer.save
                format.html { redirect_to @joboffer, notice: "Joboffer was successfully created." }
                format.json { render :show, status: :created, location: @joboffer }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @joboffer.errors, status: :unprocessable_entity }
            end
        end
    end
    
    def update
        if @joboffer.update!(joboffer_params)
            redirect_to admin_joboffer_path(@joboffer), notice: 'Job offer was successfully updated.'
        else
            render :edit, alert: "Error updating job offer"    
        end
    end

    def destroy
        @joboffer.destroy!
    
        respond_to do |format|
          format.html { redirect_to admin_joboffers_path, status: :see_other, notice: "Joboffer was successfully destroyed." }
          format.json { head :no_content }
        end
      end
    
    private
    
    def set_joboffer
        @joboffer = Joboffer.find(params[:id])
    end

    def joboffer_params
        params.require(:joboffer).permit(:title, :description, :salary)
    end 
end

app/controllers/joboffers_controller.rb
class JoboffersController < ApplicationController
  before_action :set_joboffer, only: %i[ show edit update destroy ]
  before_action :authenticate_user
  before_action :authenticate_admin, only: %i[ create edit update destroy ]
  
  before_action :set_user_profile


  # GET /joboffers or /joboffers.json
  def index
    @joboffers = Joboffer.all
  end

  # GET /joboffers/1 or /joboffers/1.json
  def show
    @joboffer = Joboffer.find(params[:id])
    @applications = @joboffer.applications
  end

  # GET /joboffers/new
  def new
    @joboffer = Joboffer.new
  end

  # GET /joboffers/1/edit
  def edit
  end

  # POST /joboffers or /joboffers.json
  def create
    @joboffer = Joboffer.new(joboffer_params)
    @joboffer.user = current_user
    @joboffer.salary = @joboffer.salary.to_s.gsub(/[^\d\.]/, '').to_f

    respond_to do |format|
      if @joboffer.save
        format.html { redirect_to @joboffer, notice: "Joboffer was successfully created." }
        format.json { render :show, status: :created, location: @joboffer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @joboffer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /joboffers/1 or /joboffers/1.json
  def update
    respond_to do |format|
      if @joboffer.update(joboffer_params)
        format.html { redirect_to @joboffer, notice: "Joboffer was successfully updated." }
        format.json { render :show, status: :ok, location: @joboffer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @joboffer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /joboffers/1 or /joboffers/1.json
  def destroy
    @joboffer.destroy!

    respond_to do |format|
      format.html { redirect_to joboffers_path, status: :see_other, notice: "Joboffer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_joboffer
      @joboffer = Joboffer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def joboffer_params
      params.require(:joboffer).permit(:title, :description)
    end

end

app/helpers/joboffers_helper.rb
module JoboffersHelper
end

app/views/joboffers/_form.html.erb
<%= form_with(model: joboffer) do |form| %>
  <% if joboffer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(joboffer.errors.count, "error") %> prohibited this joboffer from being saved:</h2>

      <ul>
        <% joboffer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="mb-3">
    <%= form.label :title,"Title for the offer", class:"form-label" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, "Full description of the offer", class:"form-label" %>
    <%= form.text_area :description,class:"form-control" %>
  </div>


  <div class="mb-3">
    <%= form.label :salary,"Offered salary", class:"form-label" %>
    <%= form.text_field :salary, onkeypress: "return event.charCode >= 48 && event.charCode <= 57", class:"form-control" %>
  </div>

  <div class="d-flex justify-content-evenly gap-3 mt-5">
    <%= form.submit "Create a new Offer", class:"btn btn-success" %>
    <%= link_to "Back", :back, class:"btn btn-secondary" %>
  </div>
  
<% end %>

app/views/joboffers/_joboffer.html.erb
<div id="<%= dom_id joboffer %>" class="card border-0">

  <div class="card-body">
    <p class="card-text">
      <%= joboffer.description %>
    </p>
    <p class="card-text">
      Salario ofrecido <%= number_to_currency(joboffer.salary) %></p>
  </div>

</div>

app/views/joboffers/edit.html.erb
<% content_for :title, "Editing joboffer" %>

<h1>Editing joboffer</h1>

<%= render "form", joboffer: @joboffer %>

<br>

<div>
  <%= link_to "Show this joboffer", @joboffer %> |
  <%= link_to "Back to joboffers", joboffers_path %>
</div>

app/views/joboffers/index.html.erb
<% content_for :title, "P -I | Joboffers" %>
<%= render "shared/h1_title", title: "Job Offers"%>

<div id="joboffers" class="container-fluid">
  <% @joboffers.each do |joboffer| %>
    <div class="row mb-3 py-3 shadow">
      <%= link_to joboffer_path(joboffer), class:"text-black text-decoration-none" do%>
        <div class="card border-0 col-10 col-xl-8 mx-auto" >
          <div class="card-body">
            <span>Published <%= time_ago_in_words(joboffer.created_at) %> ago<span>
            <h6 class="card-title fs-3"> <%= joboffer.title %> </h6>
            <p class="card-text fs-5"><%= joboffer.description %></p>
          </div>
        </div>
      <%end%>
    </div>
  <% end %>
</div>

app/views/joboffers/new.html.erb
<% content_for :title, "New joboffer" %>

<h1 class="text-center display-1">Create a new Job Offer</h1>
<div class="container-fluid my-5">
  <div class="col-10 col-md-6 mx-auto">
    <%= render "form", joboffer: @joboffer %>
  </div>
</div>

app/views/joboffers/show.html.erb
<%= render "shared/h1_title", title:@joboffer.title%>

<section class="d-block">
  <div class="col-10 mx-auto">
    <%= render @joboffer %>
  </div>
  <div class="d-flex justify-content-center">
    <% if user_signed_in? && current_user&.admin? %>
      <%= link_to 'Admin Job offer', admin_joboffer_path(@joboffer), class: 'btn btn-primary my-3' %>              
    <% end %>    
  </div>
</section>

<section class="d-block">
  <div class="col-10 mx-auto">
    <div class="card border-0">
      <div class="card-body text-center p-3">
        <% if current_user&.admin? %>
          <% if @applications&.exists? %>
            <h3 class="display-4 text-center">Actual applies<h3>
              <% @applications.each do |application| %>
            <!-- CARD APPLIES -->
                <%= link_to admin_user_path(application.user), class:"text-decoration-none" do%>
                  <div class="card my-3 border-0 border-bottom p-1">
                    <div class="row g-0">
                      <div class="col-md-6">
                        <%= image_tag application.user.profile_picture, class:"img-fluid rounded-start me-0",style:"max-width:150px;" if application.user.profile_picture.present? %>
                      </div>
                      <div class="col-md-6">
                        <div class="card-body ms-0">
                          <p class="card-text fs-6">
                            <%= application.user.name %> | <%= application.user.email %>
                          </p>
                          <p class="card-text">
                            <small class="text-muted">
                              <%= time_ago_in_words(application.created_at) %> ago
                            </small>
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                <%end%>
              <!-- END CARD APPLIES -->
              <%end%>
          <% else %>
                <h3 class="display-4 text-center">No applies yet<h3>
          <% end %>
        <% else %>
          <% if Application.exists?(user_id: current_user.id, joboffer_id: @joboffer.id) %>
            <p>You already applies this job offer, thanks.</p>
           <% else %>
            <%= button_to 'Apply this job offer', joboffer_applications_path(@joboffer), method: :post, class: 'btn btn-primary' %>
          <% end %>
        <% end %>
      </div>  
    </div>
  </div>
</section>